import React, { FunctionComponent, useEffect, useState } from 'react';
import { EditableList } from '../../../../common/listEditable';
import { Api } from '../../api';
import { Store } from 'antd/lib/form/interface';
import { InputModal, InputHelper } from '../../../../common';
import { Constants } from '../../../../default-data/constants';
import { GenerationData, EWorkflowTag } from '../../../../types';
import { ClinicalSampleNew } from '../../../../types';
import { getColumn, getEditableColumn } from '../../../../common/columnHelpers';
import { ColumnsType } from 'antd/lib/table';

type FormProps = {
    onCreateSuccessful: (count: number) => void;
    onCancel: () => void;
};

export const AutoGenerateInputForm: FunctionComponent<FormProps> = ({ onCreateSuccessful, onCancel }) => {
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [autoGeneratedSamples, setAutoGeneratedSamples] = useState<ClinicalSampleNew[]>([]);
    const [maxCounterValue, setMaxCounter] = useState<number | null>(null);

    useEffect(() => {
        async function executeFetch() {
            const maxCounter = await Api.getMaxCounter(Constants.projectId);

            setMaxCounter(maxCounter.maxCounter);
        }

        if (maxCounterValue === null) {
            executeFetch();
        }
    });

    const onCreate = (samples: ClinicalSampleNew[]) => {
        async function saveSamples() {
            try {
                await Api.postAutoGeneratedSamplesAsync(samples);

                onCreateSuccessful(samples.length);
            } catch (error) {
                setErrorMessage(error.message);
            }
        }

        saveSamples();
    };

    const onFieldsChange = (templateRaw: Store, maxCounter: number) => {
        const template: GenerationData = templateRaw as GenerationData;

        template.idSeed = maxCounter;
        console.log(maxCounter);
        const samples: ClinicalSampleNew[] = autoGenerateSamples(template);

        setAutoGeneratedSamples(samples);
    };

    const inputs: JSX.Element[] = [
        InputHelper.createFormInput('Project prefix', GenerationData.nameof('prefixProject')),
        InputHelper.createFormInput('Project suffix', GenerationData.nameof('suffixProject')),
        InputHelper.createFormInput('Description', GenerationData.nameof('description')),
        InputHelper.createFormInputNumber('Number of entries', GenerationData.nameof('numberOfEntries')),
        InputHelper.createFormSelect('Workflow tags', GenerationData.nameof('workflowTag'), [
            EWorkflowTag.LibraryGeneration,
            EWorkflowTag.SamplePreparation,
            EWorkflowTag.SwathAnalysis,
        ]),
    ];

    const handleSave = (row: ClinicalSampleNew) => {
        const newData: ClinicalSampleNew[] = [...autoGeneratedSamples];
        const index = newData.findIndex((item) => row.name === item.name);
        const item = newData[index];
        newData.splice(index, 1, {
            ...item,
            ...row,
        });

        setAutoGeneratedSamples(newData);
    };

    const columns: ColumnsType<ClinicalSampleNew> = [
        getColumn('Name', ClinicalSampleNew.nameof('name')),
        getEditableColumn('Clinical sample code', ClinicalSampleNew.nameof('clinicalSampleCode'), handleSave),
        getColumn('Processing person', ClinicalSampleNew.nameof('processingPerson')),
    ];

    return (
        <>
            <InputModal
                isVisible={true}
                errorMessage={errorMessage}
                inputs={inputs}
                placeholder={GenerationData.Default}
                title="New clinical samples"
                onValuesChange={(values: Store) => onFieldsChange(values, maxCounterValue ?? 0)}
                onCreate={async (_) => {
                    onCreate(autoGeneratedSamples);
                }}
                onCancel={onCancel}
            >
                <EditableList<ClinicalSampleNew>
                    entries={autoGeneratedSamples}
                    columns={columns}
                    rowKeySelector={(row) => row.name}
                />
            </InputModal>
        </>
    );
};

function autoGenerateSamples(templateData: GenerationData): ClinicalSampleNew[] {
    const { numberOfEntries, prefixProject, suffixProject } = templateData;
    const samples: ClinicalSampleNew[] = new Array<ClinicalSampleNew>(numberOfEntries);

    const projectId = Constants.projectId;
    const personId = Constants.personId;

    let index = 0;

    while (index < numberOfEntries) {
        const id = index + templateData.idSeed + 1;

        samples[index] = {
            projectId: Constants.projectId,
            name: `${prefixProject}_${Constants.displayProjectId}_${id}_${suffixProject}`,
            clinicalSampleCode: `${id}`, // wait: the clinical sample code - how come this is not a number? on the clinical sample this is a number!
            processingPerson: personId,
            description: templateData.description,
            workflowTag: EWorkflowTag.SamplePreparation,
            quality: 'good',
        };

        index++;
    }

    return samples;
}
