# get inspired here https://docs.docker.com/compose/compose-file/
# Use root/example as user/password credentials
version: "3.1"
networks:
  backend:

services:
  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    ports:
      - "8081:8081"

  server-app:
    image: workflow-tracker-rest-api:0.1
    restart: always
    environment:
      - WorkflowEnvironment=Docker
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      # - mongo
      - mongo-express
