# get inspired here https://docs.docker.com/compose/compose-file/
# Use root/example as user/password credentials
version: "3.1"
networks:
  backend:

services:
  mongo:
    image: mongo:3.6.18
    restart: always
    ports:
      - 27017:27017
    # the port mapping above should not be necessary. How is mongo-express not needing it? and why the server-app needs it?
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - backend
    depends_on:
      - mongo

  server-app:
    image: workflow-tracker-rest-api:0.1
    restart: always
    environment:
      - WorkflowEnvironment=Docker
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - mongo
