import { BaseApi } from '../../infrastructure/api';
import { ClinicalSampleNew } from '../../types';

export class Api {
    public static async postAutoGeneratedSamplesAsync(payload: ClinicalSampleNew[]): Promise<void> {
        return await BaseApi.postAsync(`/samples/clinical`, { samples: payload });
    }
}
