import { BaseApi } from '../../../infrastructure/api';
import { ClinicalSample, SampleNew } from '../../../types';

export class Api {
    public static async postAutoGeneratedSamplesAsync(payload: SampleNew[]): Promise<ClinicalSample[]> {
        return await BaseApi.postAsync(`/samples/clinical`, { samples: payload });
    }
}
