import React, { FunctionComponent, useState } from 'react';
import { InputModal } from '../../../../../common/inputModal';
import { GenerationData, SampleNew, EWorkflowTag } from '../../../../../types';
import { createFormInput, createFormSelect } from '../../../../../common/inputModalHelpers';
import { EditableList } from './autoGenerateResultList';
import { Api } from '../../api';
import { Constants } from '../../../../../default-data/constants';
import { Store } from 'antd/lib/form/interface';

type FormProps = {
    isActiveInputForm: boolean;
    onCreateSuccessful: (count: number) => void;
    onCancel: () => void;
};

// todo - easy - move the auto generation related files into their own folder
export const AutoGenerateInputForm: FunctionComponent<FormProps> = ({
    isActiveInputForm,
    onCreateSuccessful,
    onCancel,
}) => {
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [autoGeneratedSamples, setAutoGeneratedSamples] = useState<SampleNew[]>([]);

    const onCreate = (samples: SampleNew[]) => {
        async function saveSamples() {
            try {
                await Api.postAutoGeneratedSamplesAsync(samples);

                onCreateSuccessful(samples.length);
            } catch (error) {
                setErrorMessage(error.message);
            }
        }

        saveSamples();
    };

    const onFieldsChange = (templateRaw: Store) => {
        const template: GenerationData = templateRaw as GenerationData;

        const samples: SampleNew[] = autoGenerateSamples(template);

        setAutoGeneratedSamples(samples);
    };

    const inputs: JSX.Element[] = [
        createFormInput('Project prefix', GenerationData.nameof('prefixProject')),
        createFormInput('Project id', GenerationData.nameof('projectId')),
        createFormInput('Project suffix', GenerationData.nameof('suffixProject')),
        createFormInput('Processing person', GenerationData.nameof('processingPerson')),
        createFormInput('Description', GenerationData.nameof('description')),
        createFormInput('Number of entries', GenerationData.nameof('numberOfEntries')),
        createFormSelect('Workflow tags', GenerationData.nameof('workflowTag'), [
            EWorkflowTag.LibraryGeneration,
            EWorkflowTag.SamplePreparation,
            EWorkflowTag.SwathAnalysis,
        ]),
    ];

    return (
        <>
            <InputModal
                isVisible={isActiveInputForm}
                errorMessage={errorMessage}
                inputs={inputs}
                placeholder={GenerationData.Default}
                title="New clinical samples"
                onValuesChange={onFieldsChange}
                onCreate={async (_) => {
                    onCreate(autoGeneratedSamples);
                }}
                onCancel={onCancel}
            >
                <EditableList
                    entries={autoGeneratedSamples}
                    onListChanged={(samples: SampleNew[]) => {
                        setAutoGeneratedSamples(samples);
                    }}
                />
            </InputModal>
        </>
    );
};

function autoGenerateSamples(templateData: GenerationData): SampleNew[] {
    const { numberOfEntries, prefixProject, suffixProject, projectId } = templateData;
    const samples: SampleNew[] = new Array(numberOfEntries);

    let index = 0;
    while (index < numberOfEntries) {
        const id = index + 1;

        samples[index] = {
            projectId: Constants.projectId, // wait: the project id should come from the template data (the unique project id from the db)
            name: `${prefixProject}_${projectId}_${id}_${suffixProject}`,
            parentSampleId: 'parent_sample_id',
            protocolId: -1,
            clinicalSampleCode: `${id}`, // wait: the clinical sample code - how come this is not a number? on the clinical sample this is a number!
            processingPerson: templateData.processingPerson,
            description: templateData.description,
            sampleCounter: id, // wait: the sampleCounter should be removed from the frontend. It is completely wrong to have it here
            workflowTag: EWorkflowTag.SamplePreparation,
        };

        index++;
    }

    return samples;
}
